### ISSUE TITLE
Extract authentication & authorization to separate service

### ISSUE THREAD

**Issue by dantetemplar** [one-zero-eight/InNoHassle-Accounts#1]
- [x] Login via Innopolis SSO.
- [x] Connect telegram
- [x] Login via telegram
- [x] Email code flow
- [x] Bind other services: sports site (system should store tokens + regularly renew via refresh token), telegram (store id + regularly query user data to keep username up to date)
- [x] Easy login on trusted sites (InNoHassle site).
- [ ] Easy login to trusted bots (official InNoHassle bot).
- [x] Login for third-party sites and bots (the developer has to register their app somehow).
- [x] Authentication in Telegram Web App; via Telegram LoginUrl.
- [ ] Different access: non-Inopolis people can't use Events; Music room admins; Events admins; ban in Music room; not connected sport can't use sport features.
- [ ] Profile management: select avatar, add description, fullname
- [ ] SDKs for TypeScript and Python
